version: "3"

services:
  nginx:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./client/build:/usr/share/nginx/html
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3500:3500"
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
