name: Frontend Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      - name: Install pm2 globally
        run: npm install -g pm2

      - name: Install dependencies and build frontend
        working-directory: ./client
        run: |
          npm i --force
          CI=false npm run build
          
      - name: Copy frontend build files
        run: |
          sudo cp -r client/build/* /var/www/html/
          
      - name: Restart pm2
        working-directory: ./backend
        env:
          NODE_ENV: production
          MONGO_URL: ${{ secrets.MONGODB_URL }}
          PORT: ${{ secrets.PORT }}
          ACCESS_TOKEN_SECRET: ${{ secrets.JWT_ACCESS_TOKEN }}
        run: |
          npm i --force
          pm2 start server.js --watch
